Question 1

In [ ]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    ans = numpy.array(arr[::-1],float)
    return ans

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


Question 2

In [ ]:
import numpy
arr = numpy.array(input().split(' '),int)
print(arr.reshape(3,3))

9 8 5 6 3 2 7 4 1
[[9 8 5]
 [6 3 2]
 [7 4 1]]


Question 3

In [ ]:
import numpy
x, y = map(int, input().split())
arr = numpy.array([input().strip().split() for _ in range(x)], int)
print(arr.transpose())
print(arr.flatten())

2 2
6 5
8 9
[[6 8]
 [5 9]]
[6 5 8 9]


Question 4


In [ ]:
import numpy as np
x, y, z = map(int,input().split())
arrA = np.array([input().split() for _ in range(x)],int)
arrB = np.array([input().split() for _ in range(y)],int)
print(np.concatenate((arrA, arrB), axis = 0))

4 3 2
1 2
1 2
2 1
1 2
1 2
3 4
3 4
[[1 2]
 [1 2]
 [2 1]
 [1 2]
 [1 2]
 [3 4]
 [3 4]]


Question 5

In [ ]:
import numpy
arr = tuple(map(int,input().split()))
print(numpy.zeros(arr,int))
print(numpy.ones(arr,int))

3 
[0 0 0]
[1 1 1]


Question 6

In [ ]:
import numpy
numpy.set_printoptions(sign=' ')
x, y = map(int, input().split())
e = numpy.eye(x, y)
print(e)

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Question 7

In [ ]:
import numpy
n,m = map(int,input().split())
a = numpy.array([input().split() for _ in range(n)],int)
b = numpy.array([input().split() for _ in range(n)],int)
print(a+b,a-b,a*b,a//b,a%b,a**b,sep="\n")


1 2
1 2 3 4 
5 6  7  8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


Question 8

In [ ]:
import numpy
numpy.set_printoptions(sign=' ')
arr = numpy.array(input().split(),float)
print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


Question 9

In [ ]:
import numpy
x, y = map(int, input().split())
arr = numpy.array([input().split() for i in range(x)], int)
print(numpy.prod(numpy.sum(arr, axis = 0), axis = None))


2 2
1 2
3 4
24


Question 10 

In [ ]:
import numpy
x, y = map(int, input().split())
A = numpy.array([input().split() for i in range(x)],dtype = int)
print(numpy.max(numpy.min(A, axis=1), axis=0))


4 2
2 5
1 2
3 6
7 4
4


Question 11

In [1]:
import numpy
N, M = map(int, input().split())
A = numpy.array([input().split() for i in range(N)], dtype =float)
print(numpy.mean(A, axis =1))
print(numpy.var(A, axis =0))
print(round((numpy.std(A)),12))


2 2
1 1
3 4
[1.  3.5]
[1.   2.25]
1.299038105677


Question 12

In [ ]:
import numpy
N = int(input())
A = numpy.array([input().split() for i in range(N)], dtype =int)
B = numpy.array([input().split() for i in range(N)], dtype =int)
C = numpy.dot(A,B)
print(C)


2
1 2
3 1
1 2
3 1
[[7 4]
 [6 7]]


Question 13

In [ ]:
import numpy
a = numpy.array(input().split() , int)
b = numpy.array(input().split() , int)
print(numpy.inner(a, b))
print(numpy.outer(a, b))


0 1
2 3
3
[[0 0]
 [2 3]]


Question 14

In [ ]:
import numpy
m = numpy.array(input().split(), float)
n = float(input())
print(numpy.polyval(m, n))


1.1 2 3
3
18.900000000000002


Question 15

In [ ]:
import numpy
numpy.set_printoptions(legacy='1.13')

N = int(input())

A = numpy.array([input().split() for i in range(N)], float)
print(numpy.linalg.det(A))


2
1.1 2.2
3.1 2.1
-4.51
